import { Footer, Header } from "#/components";
import "./globals.css";
import { Providers } from "./providers";
import type { Metadata } from "next";
import "pigment-ui/colors";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Pigment UI",
  description: "Generated by Pigment UI",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
